"""empty message

Revision ID: 1efc7b0411c6
Revises: 
Create Date: 2018-09-20 15:51:09.509264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efc7b0411c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'anunciantes', ['partner'])
    op.add_column('user', sa.Column('extra', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'extra')
    op.drop_constraint(None, 'anunciantes', type_='unique')
    # ### end Alembic commands ###
