"""empty message

Revision ID: 594a53aed108
Revises: 1efc7b0411c6
Create Date: 2018-09-23 16:52:29.327155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594a53aed108'
down_revision = '1efc7b0411c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anunciantes', sa.Column('uniquekey', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'anunciantes', ['uniquekey'])
    op.create_unique_constraint(None, 'anunciantes', ['pid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'anunciantes', type_='unique')
    op.drop_constraint(None, 'anunciantes', type_='unique')
    op.drop_column('anunciantes', 'uniquekey')
    # ### end Alembic commands ###
