"""empty message

Revision ID: 852db76eb9dd
Revises: 
Create Date: 2019-05-20 19:09:22.909576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '852db76eb9dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lang', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lang')
    # ### end Alembic commands ###
