"""empty message

Revision ID: b19389220678
Revises: 594a53aed108
Create Date: 2018-09-24 11:25:29.073879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b19389220678'
down_revision = '594a53aed108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anunciantes', sa.Column('imagem', sa.Boolean(), nullable=True))
    op.add_column('anunciantes', sa.Column('log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anunciantes', 'log')
    op.drop_column('anunciantes', 'imagem')
    # ### end Alembic commands ###
