"""empty message

Revision ID: ea3e714b68c0
Revises: b19389220678
Create Date: 2018-09-24 13:44:57.789567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea3e714b68c0'
down_revision = 'b19389220678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anunciantes', sa.Column('mastertag_imagem', sa.Boolean(), nullable=True))
    op.drop_column('anunciantes', 'imagem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anunciantes', sa.Column('imagem', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('anunciantes', 'mastertag_imagem')
    # ### end Alembic commands ###
